### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by serpro69** [MSDehghan/AnsiblePlugin#19]
Hi,

I see last release and code change was ~2 years ago.
Do you have further plans to maintain this plugin or has it been abandoned?

**Comment by MSDehghan** [comment]
Hi,
Actually I have plans to maintain this project in future but unfortunately last two years I was too busy with my master thesis and university classes and I have no free time to work on open-source projects :(
I hope to be able to continue this project this year.

**Comment by yuri-becker** [comment]
@MSDehghan Hi, I would be interested in contributing. Are you available to accept pull requests?
