### ISSUE TITLE
Wich version of ansible does pluggin support?

### ISSUE THREAD

**Issue by tutunak** [MSDehghan/AnsiblePlugin#6]
I've tried to use this plugin for ansible version 2.10, but accomplishing doesn't work for e.g ansible.builtin.file. Do you have a plan to support the newest version of ansible in the near future? But anyway you are doing a great job. Other plugins I've met were awful. For the last time I've been using JSON schemas in IDEA but they work no so good.

**Comment by MSDehghan** [comment]
First of all, sorry for late answer. I totally forgot to write the answer.
The plugin currently support ansible 2.9. Ansible

**Comment by MSDehghan** [comment]
First of all, sorry for late answer. I totally forgot to write the answer.
The plugin currently support ansible 2.9. Ansible collections and FQCN will be supported soon.

I will try my best to do it as soon as possible.

**Comment by tutunak** [comment]
Thank you for your response. I'm glad that you have plans to support the newest version of ansible.

**Comment by sandikata** [comment]
Hello, are there plans of supporting ansible 2.10+ ?
because with 2.14 there are a lot of changes and this plugin just not work with them.
